### ISSUE TITLE
Add Color and Color Temperature Control to Light Accessory

### ISSUE THREAD

**Issue by resonaura** [sinricpro/homebridge-sinricpro#2]
Hello!

Thank you for the great work on this plugin! I would like to request a new feature for the Light accessory.

Please add support for controlling both color and color temperature for lights in the Light accessory. This would greatly enhance the user experience for those of us making DIY smart bulbs that support these features.

I have two self-crafted smart bulbs that can change both color and color temperature, but currently, I can only control brightness via Apple Home App. It would be very helpful to have full control over these capabilities through this plugin.

Thank you for considering this feature! I’m looking forward to any updates or progress on this.

**Comment by kakopappa** [comment]
Thanks. will take a look

**Comment by resonaura** [comment]
Appreciate it

**Comment by resonaura** [comment]
Hi, sorry to bother you. Just want to know if there are any updates :)

**Comment by kakopappa** [comment]
Sorry haven’t looked at it yet. Wrapping up the next version update now. Once it’s done will take a look

**Comment by resonaura** [comment]
Ok, no worries. Thank you!

**Comment by resonaura** [comment]
Hi @kakopappa,

I wanted to let you know that I have submitted a Pull Request to address [this issue](https://github.com/sinricpro/homebridge-sinricpro/issues/2). The PR includes the following changes:

- Added support for Hue, Saturation, and ColorTemperature characteristics
- Integrated Prettier for improved code formatting
- Updated the version to 1.1.3

I have tested these changes on my devices, and everything is functioning as expected. You can review the Pull Request [here](https://github.com/sinricpro/homebridge-sinricpro/pull/3)

Please let me know if you have any questions or need further adjustments. Looking forward to your feedback!

Thank you and have a nice day!

Best regards,
Andrii Vynohradov

**Comment by kakopappa** [comment]
Hi @resonaura thanks a lot for the PR . looks good. I will merge.

**Comment by resonaura** [comment]
Thank you too! ☺️

**Comment by resonaura** [comment]
Hi @kakopappa, sorry to bother you again. It looks like the recent changes in the PR haven't been reflected in the latest npm release. Would you mind publishing a new version to npm when you get a chance? It would really help to have the updated version available.

Thanks again for your help and for merging the PR!

**Comment by kakopappa** [comment]
Thanks for letting me know. Will publish now.

**Comment by kakopappa** [comment]
Done.  
![image](https://github.com/user-attachments/assets/2e6c3832-154d-458f-a0e3-9b8209e209d6)

**Comment by resonaura** [comment]
Thank you!
